/* Generated By:JavaCC: Do not edit this line. ProjLangParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProjLangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int let = 5;
  /** RegularExpression Id. */
  int val = 6;
  /** RegularExpression Id. */
  int end = 7;
  /** RegularExpression Id. */
  int in = 8;
  /** RegularExpression Id. */
  int fun = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int THEN = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int lp = 13;
  /** RegularExpression Id. */
  int rp = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int not = 17;
  /** RegularExpression Id. */
  int assn_op = 18;
  /** RegularExpression Id. */
  int equal = 19;
  /** RegularExpression Id. */
  int less = 20;
  /** RegularExpression Id. */
  int addop = 21;
  /** RegularExpression Id. */
  int mulop = 22;
  /** RegularExpression Id. */
  int semicolon = 23;
  /** RegularExpression Id. */
  int num = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int id = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"let\"",
    "\"val\"",
    "\"end\"",
    "\"in\"",
    "\"fun\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"(\"",
    "\")\"",
    "\"while\"",
    "\"do\"",
    "\"!\"",
    "\":=\"",
    "\"=\"",
    "\"<\"",
    "<addop>",
    "<mulop>",
    "\";\"",
    "<num>",
    "\"true\"",
    "\"false\"",
    "<id>",
    "\"{\"",
    "\"}\"",
  };

}
